# Generated by Django 5.2.7 on 2025-10-16 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=512, unique=True)),
                ('plain_text_paragraphs', models.JSONField(default=list)),
                ('is_disambiguation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_page_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('source_title', models.CharField(db_index=True, max_length=512, unique=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='search_engine.article')),
            ],
        ),
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_title', models.CharField(max_length=512)),
                ('anchor_text', models.CharField(blank=True, max_length=512)),
                ('from_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_links', to='search_engine.article')),
                ('to_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_links', to='search_engine.article')),
            ],
            options={
                'indexes': [models.Index(fields=['from_article'], name='search_engi_from_ar_c7d6ea_idx'), models.Index(fields=['to_article'], name='search_engi_to_arti_e48011_idx'), models.Index(fields=['to_title'], name='search_engi_to_titl_10e482_idx')],
            },
        ),
    ]
