# Generated by Django 5.2.7 on 2025-10-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_tfidf'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tfidfindex',
            new_name='search_engi_article_f28b23_idx',
            old_name='search_arti_articl_idx',
        ),
    ]
