# Generated by Django 5.2.7 on 2025-10-17 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_rename_search_arti_articl_idx_search_engi_article_f28b23_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='internallink',
            name='from_page_id',
            field=models.PositiveBigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='from_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_links', to='search_engine.article'),
        ),
        migrations.AddIndex(
            model_name='internallink',
            index=models.Index(fields=['from_page_id'], name='search_engi_from_pa_20b16f_idx'),
        ),
    ]
