# Generated by Django 5.2.7 on 2025-10-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_internallink_from_page_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_idf_score', models.FloatField(default=0.0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverted_entries', to='search_engine.article')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverted_entries', to='search_engine.vocabulary')),
            ],
            options={
                'indexes': [models.Index(fields=['term', 'tf_idf_score'], name='search_engi_term_id_7cee1e_idx'), models.Index(fields=['article'], name='search_engi_article_96c9a7_idx')],
                'unique_together': {('term', 'article')},
            },
        ),
        migrations.CreateModel(
            name='PageRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('iteration_count', models.PositiveIntegerField(default=0)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagerank', to='search_engine.article')),
            ],
            options={
                'indexes': [models.Index(fields=['-score'], name='search_engi_score_293842_idx')],
            },
        ),
    ]
