# Generated by Django 5.2.7 on 2025-10-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0005_invertedindex_pagerank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
