# Generated by Django 5.2.7 on 2025-10-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='paragraph_token_counts',
            field=models.JSONField(default=list),
        ),
    ]
