# Generated by Django 5.2.7 on 2025-10-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0007_article_paragraph_token_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfidfindex',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='anchor_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='internallink',
            name='to_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='term',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Redirect',
        ),
        migrations.DeleteModel(
            name='TFIDFIndex',
        ),
    ]
