# Generated by Django 4.2.24 on 2025-10-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0008_remove_tfidfindex_article_alter_article_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagerank',
            name='iteration_count',
        ),
        migrations.RemoveField(
            model_name='pagerank',
            name='last_computed',
        ),
    ]
